linkPrefix = "/doxity-simpleton"
name = "doxity-simpleton"
version = "1.0.0"
description = "Solidity Documentation"
buildTime = 2018-05-07T17:17:12.064Z
target = "doxity"
src = "contracts/*"
dir = "pages/docs"
out = "docs"
author = "Ryan Hendricks"
homepage = "https://ryanhendricks.github.io/doxity-simpleton/"

[interaction]